// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azaiqesbozwjnwgmccth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6YWlxZXNib3p3am53Z21jY3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTMxOTMsImV4cCI6MjA3MDQyOTE5M30.eCkPxEUrQ_3WX1EP6q8sFfhIj6bkMwcv2EoLfHTcLB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});